name: famooshed_vendor
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  #for dynamic ui
  flutter_screenutil: ^5.3.1

  #for state management
  get: ^4.6.1
  get_storage: ^2.0.3

  image_picker: ^0.8.5
  image_cropper: ^3.0.2

  #for date formatting
  intl: ^0.18.0

  octo_image: ^1.0.1
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  dotted_border: ^2.0.0+3
  expansion_tile_card: ^2.0.0
  fl_chart: ^0.62.0
  #  sweet_nav_bar: ^1.0.5
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  jiffy: ^6.2.1
  flutter_advanced_drawer: ^1.3.5
  image: ^4.0.17
  number_paginator: ^0.2.3
  dio: ^5.2.1+1
  http: ^0.13.6
  syncfusion_flutter_charts: 21.2.4
  #  flutter_datetime_picker: 1.5.1

  flutter_google_map_polyline_point:
  flutter_google_places_hoc081098: 1.2.0
  google_api_headers: 1.6.0
  google_maps_flutter:
  google_maps_webservice: 0.0.20-nullsafety.5
  geolocator: 9.0.2
  dropdown_search: 5.0.6

  #  sign_in_with_apple: 5.0.0

  firebase_core: 2.15.0
  firebase_messaging: 14.6.5
  cloud_firestore: 4.8.4
  flutter_local_notifications: 15.1.0+1
  #  firebase_auth: 4.7.2
  #  google_sign_in: 6.1.4

  url_launcher: 6.1.11
  flutter_datetime_picker_plus: 2.0.0
  popover: 0.2.8+2

  mixpanel_flutter: 2.1.1

  webview_flutter: 4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # dart run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.1.0
  # dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_native_splash:create
  flutter_native_splash: ^2.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/merchant_app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/

dependency_overrides:
  http: ^1.1.0
